"""0001_init_schema

Revision ID: baa4932d9a29
Revises: None
Create Date: 2025-11-10 00:59:07.964637
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'baa4932d9a29'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('psp_webhook_events',
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('psp_ref', sa.String(length=100), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_psp_event_id')
    )
    with op.batch_alter_table('psp_webhook_events', schema=None) as batch_op:
        batch_op.create_index('ix_psp_webhook_events_kind', ['kind'], unique=False)
        batch_op.create_index('ix_psp_webhook_events_received', ['received_at'], unique=False)

    op.create_table('spend_categories',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spend_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spend_categories_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('alerts',
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('ix_alerts_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_type'), ['type'], unique=False)

    op.create_table('allowed_recipients',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'recipient_id', name='uq_allowed_pair')
    )
    with op.batch_alter_table('allowed_recipients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allowed_recipients_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_allowed_recipients_recipient_id'), ['recipient_id'], unique=False)

    op.create_table('certified_accounts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('certified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.Enum('BASIC', 'GOLD', name='certificationlevel'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('escrow_agreements',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('amount_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'FUNDED', 'RELEASABLE', 'RELEASED', 'REFUNDED', 'CANCELLED', name='escrowstatus'), nullable=False),
    sa.Column('release_conditions_json', sa.JSON(), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount_total >= 0', name='ck_escrow_amount_total_non_negative'),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('escrow_agreements', schema=None) as batch_op:
        batch_op.create_index('ix_escrow_deadline', ['deadline_at'], unique=False)
        batch_op.create_index('ix_escrow_status', ['status'], unique=False)

    op.create_table('merchants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('is_certified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['spend_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_merchants_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_merchants_name'), ['name'], unique=True)

    op.create_table('transactions',
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'REJECTED', 'FAILED', name='transactionstatus'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_transaction_positive_amount'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_transactions_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_transactions_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index('ix_transactions_status', ['status'], unique=False)

    op.create_table('allowed_payees',
    sa.Column('escrow_id', sa.Integer(), nullable=False),
    sa.Column('payee_ref', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('daily_limit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_limit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('spent_today', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('spent_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('last_reset_at', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('daily_limit IS NULL OR daily_limit >= 0', name='ck_allowed_payee_daily_limit'),
    sa.CheckConstraint('spent_today >= 0', name='ck_allowed_payee_spent_today_non_negative'),
    sa.CheckConstraint('spent_total >= 0', name='ck_allowed_payee_spent_total_non_negative'),
    sa.CheckConstraint('total_limit IS NULL OR total_limit >= 0', name='ck_allowed_payee_total_limit'),
    sa.ForeignKeyConstraint(['escrow_id'], ['escrow_agreements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('escrow_id', 'payee_ref', name='uq_allowed_payee_ref')
    )
    with op.batch_alter_table('allowed_payees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allowed_payees_escrow_id'), ['escrow_id'], unique=False)

    op.create_table('allowed_usages',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(merchant_id IS NOT NULL AND category_id IS NULL) OR (merchant_id IS NULL AND category_id IS NOT NULL)', name='ck_allowed_usage_exactly_one_target'),
    sa.ForeignKeyConstraint(['category_id'], ['spend_categories.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'category_id', name='uq_allowed_usage_category'),
    sa.UniqueConstraint('owner_id', 'merchant_id', name='uq_allowed_usage_merchant')
    )
    with op.batch_alter_table('allowed_usages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allowed_usages_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_allowed_usages_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_allowed_usages_owner_id'), ['owner_id'], unique=False)

    op.create_table('escrow_deposits',
    sa.Column('escrow_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_escrow_deposit_positive_amount'),
    sa.ForeignKeyConstraint(['escrow_id'], ['escrow_agreements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('escrow_deposits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escrow_deposits_escrow_id'), ['escrow_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_escrow_deposits_idempotency_key'), ['idempotency_key'], unique=True)

    op.create_table('escrow_events',
    sa.Column('escrow_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['escrow_id'], ['escrow_agreements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('escrow_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escrow_events_escrow_id'), ['escrow_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_escrow_events_idempotency_key'), ['idempotency_key'], unique=False)

    op.create_table('milestones',
    sa.Column('escrow_id', sa.Integer(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('proof_type', sa.String(length=50), nullable=False),
    sa.Column('validator', sa.String(length=50), nullable=False),
    sa.Column('geofence_lat', sa.Float(), nullable=True),
    sa.Column('geofence_lng', sa.Float(), nullable=True),
    sa.Column('geofence_radius_m', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('WAITING', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'PAYING', 'PAID', name='milestonestatus'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_milestone_positive_amount'),
    sa.CheckConstraint('geofence_radius_m IS NULL OR geofence_radius_m >= 0', name='ck_milestone_geofence_radius_non_negative'),
    sa.CheckConstraint('idx > 0', name='ck_milestone_positive_idx'),
    sa.ForeignKeyConstraint(['escrow_id'], ['escrow_agreements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('escrow_id', 'idx', name='uq_milestone_idx')
    )
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milestones_escrow_id'), ['escrow_id'], unique=False)

    op.create_table('purchases',
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2, asdecimal=False), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('AUTHORIZED', 'COMPLETED', 'REJECTED', name='purchasestatus'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_purchase_positive_amount'),
    sa.ForeignKeyConstraint(['category_id'], ['spend_categories.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchases_category_id'), ['category_id'], unique=False)
        batch_op.create_index('ix_purchases_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_purchases_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index('ix_purchases_status', ['status'], unique=False)

    op.create_table('payments',
    sa.Column('escrow_id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('psp_ref', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'SETTLED', 'ERROR', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_payment_positive_amount'),
    sa.ForeignKeyConstraint(['escrow_id'], ['escrow_agreements.id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('psp_ref')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('ix_payments_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_escrow_id'), ['escrow_id'], unique=False)
        batch_op.create_index('ix_payments_escrow_status', ['escrow_id', 'status'], unique=False)
        batch_op.create_index('ix_payments_idempotency_key', ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_milestone_id'), ['milestone_id'], unique=False)
        batch_op.create_index('ix_payments_status', ['status'], unique=False)

    op.create_table('proofs',
    sa.Column('escrow_id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('storage_url', sa.String(length=1024), nullable=False),
    sa.Column('sha256', sa.String(length=128), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['escrow_id'], ['escrow_agreements.id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proofs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proofs_escrow_id'), ['escrow_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proofs_milestone_id'), ['milestone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proofs_sha256'), ['sha256'], unique=True)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proofs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proofs_sha256'))
        batch_op.drop_index(batch_op.f('ix_proofs_milestone_id'))
        batch_op.drop_index(batch_op.f('ix_proofs_escrow_id'))

    op.drop_table('proofs')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('ix_payments_status')
        batch_op.drop_index(batch_op.f('ix_payments_milestone_id'))
        batch_op.drop_index('ix_payments_idempotency_key')
        batch_op.drop_index('ix_payments_escrow_status')
        batch_op.drop_index(batch_op.f('ix_payments_escrow_id'))
        batch_op.drop_index('ix_payments_created_at')

    op.drop_table('payments')
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_index('ix_purchases_status')
        batch_op.drop_index(batch_op.f('ix_purchases_sender_id'))
        batch_op.drop_index(batch_op.f('ix_purchases_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_purchases_idempotency_key'))
        batch_op.drop_index('ix_purchases_created_at')
        batch_op.drop_index(batch_op.f('ix_purchases_category_id'))

    op.drop_table('purchases')
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestones_escrow_id'))

    op.drop_table('milestones')
    with op.batch_alter_table('escrow_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escrow_events_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_escrow_events_escrow_id'))

    op.drop_table('escrow_events')
    with op.batch_alter_table('escrow_deposits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escrow_deposits_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_escrow_deposits_escrow_id'))

    op.drop_table('escrow_deposits')
    with op.batch_alter_table('allowed_usages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allowed_usages_owner_id'))
        batch_op.drop_index(batch_op.f('ix_allowed_usages_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_allowed_usages_category_id'))

    op.drop_table('allowed_usages')
    with op.batch_alter_table('allowed_payees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allowed_payees_escrow_id'))

    op.drop_table('allowed_payees')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_status')
        batch_op.drop_index(batch_op.f('ix_transactions_sender_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_receiver_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_idempotency_key'))
        batch_op.drop_index('ix_transactions_created_at')

    op.drop_table('transactions')
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merchants_name'))
        batch_op.drop_index(batch_op.f('ix_merchants_category_id'))

    op.drop_table('merchants')
    with op.batch_alter_table('escrow_agreements', schema=None) as batch_op:
        batch_op.drop_index('ix_escrow_status')
        batch_op.drop_index('ix_escrow_deadline')

    op.drop_table('escrow_agreements')
    op.drop_table('certified_accounts')
    with op.batch_alter_table('allowed_recipients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allowed_recipients_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_allowed_recipients_owner_id'))

    op.drop_table('allowed_recipients')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_type'))
        batch_op.drop_index('ix_alerts_created_at')

    op.drop_table('alerts')
    op.drop_table('users')
    with op.batch_alter_table('spend_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spend_categories_code'))

    op.drop_table('spend_categories')
    with op.batch_alter_table('psp_webhook_events', schema=None) as batch_op:
        batch_op.drop_index('ix_psp_webhook_events_received')
        batch_op.drop_index('ix_psp_webhook_events_kind')

    op.drop_table('psp_webhook_events')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
